apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: demo-server
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: demo-server                                  # 7
    spec:
      containers:
        - image: deploer/demo-server-arm
          imagePullPolicy: Always                         # 8
          name: demo-server
          ports:
            - containerPort: 1234