apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: demo-server2
  labels:
    app: demo-server                                  # 2
spec:                                                # 3
  containers:
    - image: deploer/demo-server-arm # 4
      name: demo-server                              # 5
      ports:
        - containerPort: 1234