apiVersion: v1
kind: Service              # 1
metadata:
  name: demo-server-lb
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 1234               # 3
    protocol: TCP          # 4
    targetPort: 1234         # 5
  selector:                # 6
    app: demo-server       # 7